import type { Metadata } from "next";
import "../../styles/styles.scss";

import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { checkIsPublicRoute } from "@/utils/check-route";
import { usePathname } from "next/navigation";
import { ClerkProvider, SignedIn, SignedOut } from "@clerk/nextjs";
import { UserProvider } from "@/context/UserContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const path = usePathname();

  // const isPublic = checkIsPublicRoute(path);

  return (
    <ClerkProvider>
      <html lang="pt-br">
        <body className="selection:bg-accent selection:text-white">
          <SignedIn>
            <UserProvider>{children}</UserProvider>
          </SignedIn>
          <SignedOut>{children}</SignedOut>
        </body>
      </html>
    </ClerkProvider>
  );
}
